# =============================================================================
# utils.R — Shared helpers for all figure scripts
# Source this at the top of each figure script:
#   source("R/figures/utils.R")
# =============================================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(patchwork)
  library(scales)
})

# ── Paths (relative to repo root) ─────────────────────────────────────────────
# Per-cell CSVs (large; generated by 01_extract_seaad.R or from ADNI access)
DATA_FULL <- "data/processed/"

# Bin-level means (included in repo — sufficient for all figures)
DATA_BIN  <- "data/sample/"

# Figure output
FIG_OUT   <- "output/figures/"
dir.create(FIG_OUT, recursive = TRUE, showWarnings = FALSE)

# ── Theme ─────────────────────────────────────────────────────────────────────
theme_paper <- theme_bw(base_size = 11) +
  theme(
    plot.title       = element_text(face = "bold", size = 13, hjust = 0),
    axis.title       = element_text(size = 11),
    axis.text        = element_text(size = 9),
    legend.text      = element_text(size = 8),
    legend.title     = element_text(size = 9, face = "bold"),
    legend.position  = "bottom",
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "#EBF5FB"),
    strip.text       = element_text(face = "bold")
  )

dx_colors <- c("CN" = "#4DAF4A", "MCI" = "#FF7F00", "DEM" = "#E41A1C")

# ── Gene composites ───────────────────────────────────────────────────────────
ANLS_GENES    <- c("SLC2A1", "LDHA", "SLC16A1")
VATPASE_GENES <- c("ATP6V1A","ATP6V1B2","ATP6V0D1","ATP6V0A1",
                   "ATP6V1C1","ATP6V1E1","ATP6V1H","ATP6V0C","ATP6V0E1","ATP6V0B")
VATPASE_N     <- c("ATP6V1A","ATP6V1B2","ATP6V0A1","ATP6V0C","ATP6V0D1","ATP6V1E1")

add_composites_astro <- function(df) {
  df$ANLS    <- rowMeans(df[, intersect(ANLS_GENES,    names(df)), drop = FALSE], na.rm = TRUE)
  df$VATpase <- rowMeans(df[, intersect(VATPASE_GENES, names(df)), drop = FALSE], na.rm = TRUE)
  df$MCT4    <- df$SLC16A3
  ed_genes   <- c("SLC2A1","LDHA","SLC16A1","PKM","HK1")
  df$ED_energy <- rowMeans(df[, intersect(ed_genes, names(df)), drop = FALSE], na.rm = TRUE)
  df$ED_ratio  <- df$ED_energy / df$VATpase
  df
}

add_composites_neuron <- function(df) {
  df$VATPase <- rowMeans(df[, intersect(VATPASE_N, names(df)), drop = FALSE], na.rm = TRUE)
  df
}

# ── Statistics helpers ────────────────────────────────────────────────────────
partial_cor <- function(x, y, z) {
  ok <- complete.cases(x, y, z)
  if (sum(ok) < 10) return(list(r = NA, p = NA, rx = NA, ry = NA))
  rx <- residuals(lm(x[ok] ~ z[ok]))
  ry <- residuals(lm(y[ok] ~ z[ok]))
  ct <- cor.test(rx, ry)
  list(r = ct$estimate, p = ct$p.value, rx = rx, ry = ry)
}

partial_cor_double <- function(x, y, z1, z2) {
  ok <- complete.cases(x, y, z1, z2)
  if (sum(ok) < 10) return(list(r = NA, p = NA))
  rx <- residuals(lm(x[ok] ~ z1[ok] + z2[ok]))
  ry <- residuals(lm(y[ok] ~ z1[ok] + z2[ok]))
  ct <- cor.test(rx, ry)
  list(r = ct$estimate, p = ct$p.value)
}

partial_cor_triple <- function(x, y, z1, z2, z3) {
  ok <- complete.cases(x, y, z1, z2, z3)
  if (sum(ok) < 10) return(list(r = NA, p = NA))
  rx <- residuals(lm(x[ok] ~ z1[ok] + z2[ok] + z3[ok]))
  ry <- residuals(lm(y[ok] ~ z1[ok] + z2[ok] + z3[ok]))
  ct <- cor.test(rx, ry)
  list(r = ct$estimate, p = ct$p.value)
}

norm_base <- function(vals, bins) vals / vals[which.min(bins)]

get_slope <- function(df, col, bins) {
  d    <- df[df$bin %in% bins, ]
  base <- d[[col]][d$bin == min(d$bin)]
  d$norm <- d[[col]] / base
  fit  <- lm(norm ~ bin, data = d)
  s    <- summary(fit)$coefficients
  list(beta = s[2, 1], se = s[2, 2], p = s[2, 4])
}

sig_star <- function(p) {
  if (is.na(p)) return("NA")
  if (p < 0.001) "***"
  else if (p < 0.01) "**"
  else if (p < 0.05) "*"
  else "n.s."
}

# ── Save helper ───────────────────────────────────────────────────────────────
save_fig <- function(plot, filename, width = 14, height = 10) {
  path <- file.path(FIG_OUT, filename)
  ggsave(path, plot, width = width, height = height, dpi = 300, bg = "white")
  message("Saved: ", path)
}
